= IvyPot - A Gradle plugin for Off-line Repositories
:revnumber: 0.5

Not all development teams have the luxury of relying on Maven Central, Bintray for day to day development. Some of them
are still fortunate to proxy public repositories via in-house Artifactory or Nexus instances. Others have even more
strict requirements including the ability to be able to build an isolated environment. This plugin is for them. It allows
for pubic dependencies, including transitive dependencies, to be downloaded in a controlled manner and the internal
security processes to be applied to the binary files before committing them to an internal storage area.

As from 0.5 the minimum supported Gradle version in 2.8.

== Previous versions

* https://github.com/ysb33r/ivypot-gradle-plugin/tree/RELEASE_0_4_0[Release 0.4.0]
* https://github.com/ysb33r/ivypot-gradle-plugin/tree/RELEASE_0_3_7[Release 0.3.7]
* https://github.com/ysb33r/ivypot-gradle-plugin/tree/RELEASE_0_3_6[Release 0.3.6]
* https://github.com/ysb33r/ivypot-gradle-plugin/tree/RELEASE_0_3_5[Release 0.3.5]
* https://github.com/ysb33r/ivypot-gradle-plugin/tree/RELEASE_0_3_4[Release 0.3.4]
* https://github.com/ysb33r/ivypot-gradle-plugin/tree/RELEASE_0_3_2[Release 0.3.2]
* https://github.com/ysb33r/ivypot-gradle-plugin/tree/RELEASE_0_3_1[Release 0.3.1]

== Adding the plugin

.build.gradle
[source,groovy,subs="+attributes"]
----
plugins {
  id 'org.ysb33r.ivypot' version '{revnumber}'
}
----

Or for special cases you might want to do

.build.gradle
[source,groovy,subs="+attributes"]
----
buildscript {
  repositories {
      maven {
          url "https://plugins.gradle.org/m2/"
      }
  }
  dependencies {
    classpath 'org.ysb33r.gradle:ivypot:{revnumber}'
  }
}

apply plugin : 'org.ysb33r.ivypot'
----

If you are in a restricted environment, you might want to use the second approach and conditionally add the remote reference
to work only when you are in a non-restricted environment. i.e.

[source,groovy]
----
  repositories {
    if(!System.getenv('RESTRICTED')) {
      maven {
          url "https://plugins.gradle.org/m2/"
      }
    }
  }
----

You might also consider using link:https://docs.gradle.org/current/userguide/plugins.html#customPluginRepositories[pluginManagement] in `settings.gradle` for this case.

== Defining Remote Repositories

The plugin provides a default task called `syncRemoteRepositories` which is of type `org.ysb33r.gradle.ivypot.OfflineRepositorySync`.
(You are free to create more instances of this task type).

[source,groovy]
----
syncRemoteRepositories {
  repoRoot '/path/to/repo' // <1>

  repositories {  // <2>
    jcenter()
    mavenCentral()
    mavenLocal()
    maven {
      url 'http://foo/bar'
      credentials {
        username 'pig'
        password 'hog'
      }
    }

    ivy {
      url 'http://foo.bar'  // <3>
    }

  }

  configurations 'compile', 'testCompile' // <4>

  includeBuildScriptDependencies = false // <5>
}
----
<1> Defines the location of the off-line repository root. Must be an absolute path, no relative path.
<2> `repositories` in an implementation of http://gradle.org/docs/current/javadoc/org/gradle/api/artifacts/dsl/RepositoryHandler.html[RepositoryHandler]
  and therefore supports all the standard repository definitions a Gradle user would expect.
<3> Ivy repositories in all incantantions available to Gradle is supported.
<4> Restrict the configurations you would like to have added to the synchronisation process. If none are supplied,
  dependencies from all configurations will be added.
<5> Whether to add dependencies from `buildscript`. (See further down).

== Usage

For normal usage one simply has to point to the local repository. It is assumed that this repository would be committed
to some form of source control or artifact management which is accessible with the restricted environment. The layout of
this repository is a standard Ivy layout.

[source,groovy]
----
repositories {
  ivy {
    url 'file:///path/to/repo' // <1>
    layout 'gradle' // <2>
  }
}
----
<1> Define the path to the local repository here
<2> The default layout is `gradle`. If this has been changed using `repoArtifactPattern` and `repoIvyPattern`, then
  then `layout` should be set to whatever pattern is correct.

== Boostrapping plugins in a restricted environment

Just add the repository to `repositories` closure

[source,groovy]
----
buildscript {
    repositories {
      ivy {
        url 'file:///path/to/repo' // <1>
      }
    }
}
----
<1> Define the path to the local repository here

== Adding buildscript dependencies

By default buildscript dependencies will not be added to the synchronisation list. By setting `includeBuildScriptDependencies = true` in
the configuration closure of the task these will be added.

== Patterns

By default the pattern used for writing artifacts is the standard
https://docs.gradle.org/current/javadoc/org/gradle/api/artifacts/repositories/IvyArtifactRepository.html[Ivy Pattern].
This can be changed by setting

[source,groovy]
----
syncRemoteRepositories {
  repoArtifactPattern = '[organisation]/[module]/[revision]/[type]s/[artifact]-[revision](.[ext])'
  repoIvyPattern = '[organisation]/[module]/[revision]/[type]s/[artifact]-[revision](.[ext])'
}
----

NOTE: If this is not specified, the default layout which is known as 'gradle' will be used from 0.4 and onwards.
In the 0.3.x and earlier releases the default layout will be `ivy`. The change was made because it was discovered that
Gradle handles local Ivy repositories sligtly differently and that plugins such as `groovy`, `scala` and `jruby-gradle`
which relies on finding a compiler jar in a certain named way failed when used with the local `ivy` layout.

== Flat directories

The `flatDir` repository supported by Gradle is not supported as it does not make sense. The purpose of this plugin is
to cache remote repositories into a useable local repository. If a user already has a `flatDir` it does not need be be
cached and if need be it can simply be copied.

== Limitations

* The resolution process cannot be fine-tuned at present - not to the level at least which is described
  in http://gradle.org/docs/current//userguide/dependency_management.html#sec:ivy_repositories.
* There are some limitations in Apache Ivy where Maven repositories that redirect artifacts to a different URL
  will cause failures. A known case are Ruby Gems. There is currently no known workaround.
